### ISSUE TITLE
create a tendermint client using cli

### ISSUE THREAD

**Issue by en** [octopus-network/substrate-ibc#27]
We should fix this command
https://github.com/octopus-network/ibc-demo/blob/84b196c9a170dc63a14a90b544f6d3876f7e641e/cli/src/main.rs#L54

Use data like this
https://github.com/informalsystems/ibc-rs/blob/c78b793d99571df4781cec4c2cfcb18ed68098d1/guide/src/commands/queries/client.md
to create a real `MsgCreateAnyClient`.

Then send the message to a dev node, make sure the data is stored on chain, and emit events accordingly.

**Comment by en** [comment]
This task will break down into 3 phases:

- [ ] update ibc-demo with the lastest node-template
- [ ] fix cli (mostly upgrade the subxt)
- [ ] emit substrate events when the logic in ibc-rs is successfully executed

**Comment by DaviRain-Su** [comment]
> This task will break down into 3 phases:
> 
> * [ ]  update ibc-demo with the lastest node-template
> * [ ]  fix cli (mostly upgrade the subxt)
> * [ ]  emit substrate events when the logic in ibc-rs is successfully executed
This is fix cli pr: https://github.com/octopus-network/ibc-demo/pull/6
